Define the minimal set of portable functionality
jakartaee/data pull request #247
Opened 2023-09-06 20:47 UTC by otaviojava

# Changes

- Include the portability file
- rename intro file to jakarta-data.adoc

I need help on this one. Are we getting close?

https://github.com/jakartaee/data/issues/227

2023-09-07 13:47 UTC, njr-11 requested changes
There is a lot of good information here on limitations of types of different database types.  Ideally the limitations should be stated directly alongside where the requirements are declared in the specification.

We have a table of reserved keywords in the specification document, with columns,

Keyword | Description | Method signature Sample

Let’s add a fourth column, “Database Types Where Not Required”  (or the opposite if it’s more concise that way) to explicitly identify every keyword that is not required for a particular type of database. 

Based on what you wrote in this pull, for the `Or` keyword, you would list Wide-Column.

For the CrudRepository and PageableRepository methods, the information belongs in the JavaDoc of the specific method.  This is where users will first look (and it is the only place they should need to look) for identifying if they can rely on using the method.  Similarly, a Jakarta Data provider that implements the method will want to see the same information on the JavaDoc.  The method JavaDoc can also declare the exception that is raised (MappingException or UnsupportedOperationException or define a new one?) when the function is not available from the database.

Given that you can compose methods similar to those on the built-in repository interfaces, documentation also belongs in the spec document.  Add a similar “Database Types Where Not Required” column to the “Query Methods Keywords” table.

Based on what you wrote in this pull, for the `countBy` keyword, you would list Key-Value.

A footnote will be needed to address the part about the limitation of queries that do not use the identifier for Key-Value.

2023-09-08 09:23 UTC, otaviojava commented
@michael-simons could you help and give your opinions on these points, mainly the Graph part?

2023-09-08 10:15 UTC, otaviojava commented
@njr-11, what do you think?

2023-09-08 10:33 UTC, michael-simons requested changes

2023-09-08 10:33 UTC, michael-simons commented on spec/src/main/asciidoc/portability.asciidoc
> +A Graph database, a specialized NoSQL variant, excels in managing intricate data relationships, rivaling even traditional relational databases. Its unique strength lies in its ability to handle compl
```suggestion
A Graph database, a specialized NoSQL variant, excels in managing intricate data relationships, rivaling even traditional relational databases. Its unique strength lies in its ability to handle both directed and undirected edges  (or relationships) between vertices (or nodes), including the ability to store properties on both vertices and edges.```

2023-09-08 10:33 UTC, michael-simons commented on spec/src/main/asciidoc/portability.asciidoc
> +In Jakarta Data, Graph databases support advanced querying capabilities, akin to relational databases, while providing extensive support for method by query keywords. Additionally, they fully impleme
```suggestion
Graph databases usually can answer queries that returns rows with either flat objects, or collections or mixtures of them. Portability is guaranteed only for the mapping of rows to classes, for the fact that queries specified via annotations or other means are supported and that queries derived from keywords and combinations of mapped classes/properties will be translated into vendor specify query.
```

2023-09-08 15:06 UTC, njr-11 requested changes
Thanks for adding the explicit information in table form. I looked over the rest of the pull and added some review comments.

2023-09-08 15:06 UTC, njr-11 commented on spec/src/main/asciidoc/repository.asciidoc
> +Jakarta Data implementations support the following list of predicate keywords to the extent that the database is capable of the behavior. A repository method will raise `java.lang.UnsupportedOperatio
```suggestion
Jakarta Data implementations must support the following list of query-by-method keywords, except where indicated for a database type. A repository method must raise `java.lang.UnsupportedOperationException` or a more specific subclass of the exception if the database does not provide the requested functionality.
```

2023-09-08 15:56 UTC, otaviojava commented
> Thanks for adding the explicit information in table form. I looked over the rest of the pull and added some review comments.

@njr-11 thank you. All comments fixed.

2023-09-08 16:06 UTC, njr-11 commented
> > Thanks for adding the explicit information in table form. I looked over the rest of the pull and added some review comments.
> 
> @njr-11 thank you. All comments fixed.

Actually, there are still a number of review comments that are not addressed yet.  I think you may have missed them because due the quantity of comments, git defaults to minimizing some of them.  I had to click on a section to make git show them all.

2023-09-08 18:06 UTC, otaviojava commented
> > > Thanks for adding the explicit information in table form. I looked over the rest of the pull and added some review comments.
> > 
> > 
> > @njr-11 thank you. All comments fixed.
> 
> Actually, there are still a number of review comments that are not addressed yet. I think you may have missed them because due the quantity of comments, github defaults to minimizing some of them. I had to click on a section to make git show them all.

Thank you, I checked twice, I hope that I got all of those now.

2023-09-08 18:31 UTC, njr-11 approved these changes
The only remaining comment that wasn't addressed is to rewrite the following sentence,
"Portability is guaranteed only for the mapping of rows to classes, for the fact that queries specified via annotations or other means are supported and that queries derived from keywords and combinations of mapped classes/properties will be translated into vendor specify query."

There are getting to be a lot of commits on this pull already, so I'm fine if that happens under a separate pull.

2023-09-09 04:36 UTC, merged