add a constructor to CursoredPageRecord implementing an idiom from Nathan
jakartaee/data pull request #611
Opened 2024-03-29 22:37 UTC by gavinking

This wasn't completely obvious to me. Perhaps it should have been, but it wasn't.

Anyway, since it's possible to encapsulate it, we might as well.

2024-03-30 12:57 UTC, njr-11 requested changes

2024-03-30 12:57 UTC, njr-11 commented on api/src/main/java/jakarta/data/page/impl/CursoredPageRecord.java
> +                        : pageRequest.page(pageRequest.page()==0 ? 0 : pageRequest.page()-1)
Page numbers are 1 based, not 0 based.
```suggestion
                        : pageRequest.page(pageRequest.page()==1 ? 1 : pageRequest.page()-1)
```

2024-03-30 18:54 UTC, njr-11 approved these changes

2024-03-31 15:38 UTC, merged

2024-03-31 15:59 UTC, gavinking commented
Thanks 👍