use @Query and @Find for example code in chapter 4
jakartaee/data pull request #663
Opened 2024-04-05 16:58 UTC by gavinking

instead of Query by Method Name, which has been exiled to a separate document.

2024-04-08 14:39 UTC, njr-11 requested changes

2024-04-08 14:39 UTC, njr-11 commented on spec/src/main/asciidoc/repository.asciidoc
> +                            Order<User> sorts);
Prior to your changes, these examples covered 5 scenarios:

OrderBy keyword + Order param
OrderBy keyword + Sort... param
OrderBy anno + Order param
OrderBy anno + Sort... param
Query without ORDER BY + OrderBy anno + Order param

After changes, it now only covers 2 scenarios with several duplicated:

Query without ORDER BY + OrderBy anno + Order param
Query without ORDER BY + OrderBy anno + Sort... param
Query without ORDER BY + OrderBy anno + Order param
Query without ORDER BY + OrderBy anno + Sort... param
Query without ORDER BY + OrderBy anno + Order param

Adding suggestions to restore to previous:

```suggestion
Page<User> findByNameStartsWithOrderByType(String namePrefix,
                                           PageRequest pagination,
                                           Order<User> sorts);
```

2024-04-08 14:39 UTC, njr-11 commented on spec/src/main/asciidoc/repository.asciidoc
> +List<User> findByNamePrefix(String namePrefix, Sort<?>... sorts);
```suggestion
List<User> findByNameStartsWithOrderByType(String namePrefix, Sort<?>... sorts);
```

2024-04-08 14:39 UTC, njr-11 commented on spec/src/main/asciidoc/repository.asciidoc
> +                            Order<User> sorts);
```suggestion
@OrderBy(_User.AGE)
Page<User> findByNameStartsWith(String namePrefix,
                                PageRequest pagination,
                                Order<User> sorts);
```

2024-04-08 14:39 UTC, njr-11 commented on spec/src/main/asciidoc/repository.asciidoc
> +List<User> findByNamePrefix(String namePrefix, Sort<?>... sorts);
```suggestion
@OrderBy(_User.AGE)
List<User> findByNameStartsWith(String namePrefix, Sort<?>... sorts);
```

2024-04-08 14:43 UTC, gavinking commented
@njr-11 Again, I don't think we should be having examples with QbMN in the main spec, because the main spec does not define what QbMN is. I agree that there is now duplication in the examples; the best fix to that would be to simply delete a couple of them.

2024-04-08 14:44 UTC, gavinking commented
I mean, a reader of the Jakarta Data spec is going to encounter those examples and think "WTF is this `findByNameStartsWithOrderByType` stuff?"

2024-04-08 14:52 UTC, gavinking commented
Please see 9c43087b0dfcac45f031a05758acfe10a26c01a8, which removes the duplication.

2024-04-08 15:00 UTC, njr-11 commented
> @njr-11 Again, I don't think we should be having examples with QbMN in the main spec, because the main spec does not define what QbMN is. I agree that there is now duplication in the examples; the best fix to that would be to simply delete a couple of them.

Given that Query by Method Name is still part of Jakarta Data, the spec has an obligation to cover how it behaves with respect to the rest of the specification, regardless of whether it is defined in a separate PDF or not. These examples are probably not that important and it could be stated that OrderBy keyword behaves the same as OrderBy annotation here, but I don't want to start a precedent for neglecting to adequately cover Query by Method Name because of where it appears in the spec.

2024-04-08 15:05 UTC, gavinking commented
@njr-11 Then move the examples to the Query by Method Name document. I'm not sure they're needed, but I don't object to having them. I've put quite a lot of work into improving the material in that document over the weekend, but any help would be appreciated, which includes anything you think is missing and want to add.

But for sure these examples don't belong where they are right now, because the reader has never encountered a Query by Method Name, and will have no idea how to interpret the examples. Examples have to be examples of something you have properly introduced previously. You have to assume that the reader is reading the text in a linear fashion, even if that's not always the case in practice.

2024-04-11 12:44 UTC, gavinking commented
I think this should be merged. 

I insist that we should never have examples in the spec which the reader will not understand. What is the point of such an example?

2024-04-11 13:45 UTC, njr-11 approved these changes

2024-04-11 14:21 UTC, merged