Clarify null, cleanup javadoc, declare final where possible
jakartaee/data pull request #69
Opened 2022-11-05 10:16 UTC by graemerocher

2022-11-05 12:28 UTC, otaviojava approved these changes

2022-11-05 13:36 UTC, njr-11 requested changes
Thanks for tidying up the JavaDoc in all these places!  I noticed that you made the same changes to Pageable JavaDoc about non-null return types that you asked me to make in your review of #68, and this will cause merge conflicts.  Would it make sense to omit those changes from this pull to avoid the conflict?

2022-11-05 13:36 UTC, njr-11 commented on api/src/main/java/jakarta/data/repository/Slice.java
> +     * @return the next pageable; will never be {@literal null}.
This is incorrect and contradicts two lines up where it explicitly states,
"or <code>null</code> if it is known that there is no next page."

2022-11-05 13:36 UTC, njr-11 commented on api/src/main/java/jakarta/data/repository/CrudRepository.java
> +     * {@literal ids}.
Minor: unnecessary addition of blank space at end of line.

2022-11-06 10:36 UTC, graemerocher commented
thanks for the feedback, will cleanup

2022-11-07 10:05 UTC, otaviojava approved these changes

2022-11-07 14:12 UTC, njr-11 approved these changes

2022-11-07 14:18 UTC, merged